---
- name: install wordpress
  hosts: all
  gather_facts: yes
  become: yes

  # install dependencies

  tasks:
    - name: install dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - apache2
        - ghostscript
        - libapache2-mod-php
        - mysql-server
        - php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip
        - python-pymysql
        - python3-pymysql
        - python-apt
        - python3-apt

    # mysql

    - name: include role mysql
      include_role:
        name: mysql

    # wordpress

    - name: include role wordpress
      include_role:
        name: wordpress


    - name: reload apach
      service:
        name: apache2
        state: reloaded
...
